import {
  Category,
  Expense,
  ExpenseStatus,
  InsightCard,
  NotificationItem,
  Role,
  TrendPoint,
  User,
} from '../models/app.models';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-admin-1',
    name: 'Aarav Malhotra',
    email: 'vikas.yadav@autovyn.in',
    role: Role.Admin,
    title: 'Finance Administrator',
    department: 'Corporate Finance',
    avatarUrl: '/assets/avatars/admin-avatar.svg',
    assignedBudget: 275000,
    phone: '+91 98765 43010',
    location: 'Head Office, Bengaluru',
  },
  {
    id: 'usr-mgr-1',
    name: 'Rhea Sharma',
    email: 'pankaj.jhakar@autovyn.in',
    role: Role.OperationManager,
    title: 'Operations Manager',
    department: 'Dealership Operations',
    avatarUrl: '/assets/avatars/manager-avatar.svg',
    assignedBudget: 85000,
    phone: '+91 99887 66125',
    location: 'Showroom Floor, Bengaluru',
  },
  {
    id: 'usr-mgr-2',
    name: 'Kabir Saini',
    email: 'kabir.saini@auroraledger.demo',
    role: Role.OperationManager,
    title: 'Branch Operations Lead',
    department: 'Regional Operations',
    avatarUrl: '/assets/avatars/manager-secondary.svg',
    assignedBudget: 72000,
    phone: '+91 90001 22981',
    location: 'Pune Satellite Office',
  },
  {
    id: 'usr-mgr-3',
    name: 'Meera Joshi',
    email: 'meera.joshi@auroraledger.demo',
    role: Role.OperationManager,
    title: 'Facilities Manager',
    department: 'Admin & Facilities',
    avatarUrl: '/assets/avatars/manager-third.svg',
    assignedBudget: 64000,
    phone: '+91 97654 11822',
    location: 'Corporate Support Centre',
  },
];

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'tea-pantry',
    name: 'Tea and Pantry',
    description: 'Tea, sugar, cups and pantry essentials.',
    icon: 'cup',
    accent: '#06B6D4',
    monthlyBudget: 20000,
    previousSpend: 17240,
  },
  {
    id: 'milk',
    name: 'Milk',
    description: 'Fresh milk and dairy replenishment.',
    icon: 'droplet',
    accent: '#8B5CF6',
    monthlyBudget: 6000,
    previousSpend: 4820,
  },
  {
    id: 'gas',
    name: 'Gas',
    description: 'Refills for pantry and office cooking gas.',
    icon: 'flame',
    accent: '#F59E0B',
    monthlyBudget: 4500,
    previousSpend: 3900,
  },
  {
    id: 'office-snacks',
    name: 'Office Snacks',
    description: 'Snacks for staff and visitors.',
    icon: 'sparkles',
    accent: '#22C55E',
    monthlyBudget: 12000,
    previousSpend: 10820,
  },
  {
    id: 'stationery',
    name: 'Stationery',
    description: 'Mixed office stationery supplies.',
    icon: 'pen-tool',
    accent: '#4F46E5',
    monthlyBudget: 9000,
    previousSpend: 7420,
  },
  {
    id: 'pen',
    name: 'Pen',
    description: 'Pens and marker purchases.',
    icon: 'edit',
    accent: '#38BDF8',
    monthlyBudget: 2500,
    previousSpend: 1980,
  },
  {
    id: 'diary',
    name: 'Diary',
    description: 'Office diaries and planner notebooks.',
    icon: 'book-open',
    accent: '#A78BFA',
    monthlyBudget: 3000,
    previousSpend: 2240,
  },
  {
    id: 'register',
    name: 'Register',
    description: 'Attendance and workshop registers.',
    icon: 'book',
    accent: '#0EA5E9',
    monthlyBudget: 3200,
    previousSpend: 2625,
  },
  {
    id: 'laptop',
    name: 'Laptop',
    description: 'Laptop procurement and service accessories.',
    icon: 'laptop',
    accent: '#06B6D4',
    monthlyBudget: 55000,
    previousSpend: 41000,
  },
  {
    id: 'keyboard',
    name: 'Keyboard',
    description: 'Replacement keyboards.',
    icon: 'keyboard',
    accent: '#7C3AED',
    monthlyBudget: 6000,
    previousSpend: 5280,
  },
  {
    id: 'mouse',
    name: 'Mouse',
    description: 'USB and wireless mouse replacements.',
    icon: 'mouse-pointer',
    accent: '#22C55E',
    monthlyBudget: 4500,
    previousSpend: 3200,
  },
  {
    id: 'monitor',
    name: 'Monitor',
    description: 'Display accessories and replacements.',
    icon: 'monitor',
    accent: '#2563EB',
    monthlyBudget: 24000,
    previousSpend: 19850,
  },
  {
    id: 'printer-items',
    name: 'Printer Items',
    description: 'Toners, cartridges and maintenance items.',
    icon: 'printer',
    accent: '#F97316',
    monthlyBudget: 14000,
    previousSpend: 11890,
  },
  {
    id: 'paper',
    name: 'Paper',
    description: 'A4, invoice and printer paper stock.',
    icon: 'file-text',
    accent: '#94A3B8',
    monthlyBudget: 5000,
    previousSpend: 4150,
  },
  {
    id: 'internet',
    name: 'Internet',
    description: 'Broadband and backup data charges.',
    icon: 'wifi',
    accent: '#06B6D4',
    monthlyBudget: 9000,
    previousSpend: 8700,
  },
  {
    id: 'cleaning-supplies',
    name: 'Cleaning Supplies',
    description: 'Cleaning liquids, wipes and consumables.',
    icon: 'shield',
    accent: '#10B981',
    monthlyBudget: 7000,
    previousSpend: 5640,
  },
  {
    id: 'furniture-repairs',
    name: 'Furniture and Repairs',
    description: 'Office furniture fixes and service calls.',
    icon: 'tool',
    accent: '#F59E0B',
    monthlyBudget: 16000,
    previousSpend: 12500,
  },
  {
    id: 'utility-consumables',
    name: 'Utility Consumables',
    description: 'Daily operational consumables.',
    icon: 'package',
    accent: '#6366F1',
    monthlyBudget: 11000,
    previousSpend: 9325,
  },
  {
    id: 'miscellaneous',
    name: 'Miscellaneous',
    description: 'Small ad hoc office expenses.',
    icon: 'asterisk',
    accent: '#EF4444',
    monthlyBudget: 8000,
    previousSpend: 7340,
  },
  {
    id: 'staff-fooding',
    name: 'Staff Fooding Expense',
    description: 'Team meal and extended shift fooding expense.',
    icon: 'sparkles',
    accent: '#22C55E',
    monthlyBudget: 18000,
    previousSpend: 14280,
  },
  {
    id: 'customer-facility',
    name: 'Customer Facility Expense',
    description: 'Refreshments and comfort items for customers.',
    icon: 'cup',
    accent: '#06B6D4',
    monthlyBudget: 15000,
    previousSpend: 11950,
  },
  {
    id: 'staff-tea',
    name: 'Staff Tea Expenses',
    description: 'Dedicated staff tea service and beverage support.',
    icon: 'cup',
    accent: '#8B5CF6',
    monthlyBudget: 9000,
    previousSpend: 6840,
  },
];

const commonAudit = (actor: string, actorRole: Role, date: string, note: string) => [
  {
    id: `${actor}-${date}-created`,
    action: 'Expense logged',
    actor,
    actorRole,
    date,
    note,
    tone: 'info' as const,
  },
];

export const DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp-1001',
    title: 'Pantry refresh for showroom team',
    categoryId: 'tea-pantry',
    amount: 4850,
    date: '2026-04-01',
    description:
      'Tea leaves, sugar, disposable cups and coffee sachets for the first week of April.',
    vendor: 'Fresh Brew Traders',
    tags: ['pantry', 'weekly'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-01T09:45:00+05:30',
    updatedAt: '2026-04-01T12:30:00+05:30',
    receipt: {
      id: 'att-1',
      name: 'pantry-bill-apr-01.svg',
      url: '/assets/receipts/pantry-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-01T09:45:00+05:30',
        'Submitted with bill preview attached.',
      ),
      {
        id: 'apr-01-review',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T12:30:00+05:30',
        note: 'Within allocated pantry budget.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1002',
    title: 'Milk top-up for visitor lounge',
    categoryId: 'milk',
    amount: 1680,
    date: '2026-04-02',
    description: 'Morning dairy purchase for staff pantry and guest counter.',
    vendor: 'Metro Dairy Point',
    tags: ['daily', 'pantry'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-02T10:05:00+05:30',
    updatedAt: '2026-04-02T10:05:00+05:30',
    receipt: {
      id: 'att-2',
      name: 'milk-bill-apr-02.svg',
      url: '/assets/receipts/milk-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Rhea Sharma',
      Role.OperationManager,
      '2026-04-02T10:05:00+05:30',
      'Queued for finance review.',
    ),
  },
  {
    id: 'exp-1003',
    title: 'LPG cylinder refill',
    categoryId: 'gas',
    amount: 2140,
    date: '2026-04-02',
    description: 'Single cylinder refill for cafeteria pantry operations.',
    vendor: 'Prime Gas Agency',
    tags: ['utility'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.UnderReview,
    createdAt: '2026-04-02T11:20:00+05:30',
    updatedAt: '2026-04-02T11:44:00+05:30',
    receipt: {
      id: 'att-3',
      name: 'gas-bill-apr-02.svg',
      url: '/assets/receipts/gas-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-02T11:20:00+05:30',
        'Marked urgent due to pantry downtime.',
      ),
      {
        id: 'gas-check',
        action: 'Review initiated',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-02T11:44:00+05:30',
        note: 'Cross-checking vendor amount versus last refill.',
        tone: 'warning',
      },
    ],
  },
  {
    id: 'exp-1004',
    title: 'Office snack replenishment',
    categoryId: 'office-snacks',
    amount: 6980,
    date: '2026-03-29',
    description: 'Granola bars, biscuits and bottled juice for weekend sales activity.',
    vendor: 'City Wholesale Mart',
    tags: ['staff-engagement'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-29T15:12:00+05:30',
    updatedAt: '2026-03-29T18:25:00+05:30',
    receipt: {
      id: 'att-4',
      name: 'snacks-bill-mar-29.svg',
      url: '/assets/receipts/snacks-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-03-29T15:12:00+05:30',
        'Submitted for event-day usage.',
      ),
      {
        id: 'snacks-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-29T18:25:00+05:30',
        note: 'Aligned to dealership weekend campaign.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1005',
    title: 'Stationery combo pack',
    categoryId: 'stationery',
    amount: 4325,
    date: '2026-04-01',
    description: 'Markers, sticky notes, files and desk stationery.',
    vendor: 'Office Orbit',
    tags: ['supplies'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-01T13:15:00+05:30',
    updatedAt: '2026-04-01T16:10:00+05:30',
    receipt: {
      id: 'att-5',
      name: 'stationery-bill-apr-01.svg',
      url: '/assets/receipts/stationery-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-04-01T13:15:00+05:30',
        'Submitted against regional branch stock requirement.',
      ),
      {
        id: 'stationery-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T16:10:00+05:30',
        note: 'Purchase within approved stationery band.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1006',
    title: 'Premium keyboard replacement',
    categoryId: 'keyboard',
    amount: 6120,
    date: '2026-04-01',
    description: 'Mechanical keyboard replacement for finance control desk.',
    vendor: 'TechSquare Systems',
    tags: ['hardware', 'replacement'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.OverBudget,
    createdAt: '2026-04-01T14:00:00+05:30',
    updatedAt: '2026-04-01T14:20:00+05:30',
    receipt: {
      id: 'att-6',
      name: 'keyboard-bill-apr-01.svg',
      url: '/assets/receipts/hardware-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-04-01T14:00:00+05:30',
        'Submitted with urgent hardware replacement justification.',
      ),
      {
        id: 'keyboard-alert',
        action: 'Over budget flagged',
        actor: 'System',
        actorRole: Role.Admin,
        date: '2026-04-01T14:20:00+05:30',
        note: 'Category has exceeded 100 percent monthly utilization.',
        tone: 'danger',
      },
    ],
  },
  {
    id: 'exp-1007',
    title: 'Printer toner cartridge set',
    categoryId: 'printer-items',
    amount: 8840,
    date: '2026-04-02',
    description: 'Toner cartridge set for invoice printer and reporting printer.',
    vendor: 'PrintEase Solutions',
    tags: ['printing'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.UnderReview,
    createdAt: '2026-04-02T09:20:00+05:30',
    updatedAt: '2026-04-02T10:15:00+05:30',
    receipt: {
      id: 'att-7',
      name: 'printer-bill-apr-02.svg',
      url: '/assets/receipts/printer-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-04-02T09:20:00+05:30',
        'Submitted with vendor quotation attachment.',
      ),
      {
        id: 'printer-review',
        action: 'Review initiated',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-02T10:15:00+05:30',
        note: 'Comparing unit rates with prior purchase cycle.',
        tone: 'warning',
      },
    ],
  },
  {
    id: 'exp-1008',
    title: 'Broadband annual booster pack',
    categoryId: 'internet',
    amount: 9320,
    date: '2026-03-27',
    description: 'Bandwidth booster pack for finance and support systems.',
    vendor: 'SkyWire Business',
    tags: ['connectivity'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-27T10:45:00+05:30',
    updatedAt: '2026-03-27T12:00:00+05:30',
    receipt: {
      id: 'att-8',
      name: 'internet-bill-mar-27.svg',
      url: '/assets/receipts/internet-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-03-27T10:45:00+05:30',
        'Submitted as planned recurring connectivity spend.',
      ),
      {
        id: 'internet-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-27T12:00:00+05:30',
        note: 'Tagged as recurring business utility.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1009',
    title: 'Visitor lounge paper stock',
    categoryId: 'paper',
    amount: 2140,
    date: '2026-04-02',
    description: 'A4 and invoice paper stock replenishment.',
    vendor: 'PaperPort Office',
    tags: ['stock'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Draft,
    createdAt: '2026-04-02T16:12:00+05:30',
    updatedAt: '2026-04-02T16:12:00+05:30',
    receipt: {
      id: 'att-9',
      name: 'paper-bill-draft.svg',
      url: '/assets/receipts/paper-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Rhea Sharma',
      Role.OperationManager,
      '2026-04-02T16:12:00+05:30',
      'Saved as draft for later submission.',
    ),
  },
  {
    id: 'exp-1010',
    title: 'Wireless mouse replacements',
    categoryId: 'mouse',
    amount: 2940,
    date: '2026-03-30',
    description: 'Two wireless mouse replacements for reception and billing desk.',
    vendor: 'TechSquare Systems',
    tags: ['hardware'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-30T11:20:00+05:30',
    updatedAt: '2026-03-30T15:35:00+05:30',
    receipt: {
      id: 'att-10',
      name: 'mouse-bill-mar-30.svg',
      url: '/assets/receipts/hardware-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-03-30T11:20:00+05:30',
        'Submitted with workstation downtime note.',
      ),
      {
        id: 'mouse-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-30T15:35:00+05:30',
        note: 'Approved under workstation maintenance.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1011',
    title: 'Cleaning liquids and wipes',
    categoryId: 'cleaning-supplies',
    amount: 5280,
    date: '2026-03-28',
    description: 'Housekeeping consumables for customer zones and service desks.',
    vendor: 'Spark Hygiene Mart',
    tags: ['housekeeping'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-28T08:35:00+05:30',
    updatedAt: '2026-03-28T10:10:00+05:30',
    receipt: {
      id: 'att-11',
      name: 'cleaning-bill-mar-28.svg',
      url: '/assets/receipts/cleaning-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-03-28T08:35:00+05:30',
        'Submitted as recurring facilities expense.',
      ),
      {
        id: 'cleaning-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-28T10:10:00+05:30',
        note: 'Routine cleaning spend approved.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1012',
    title: 'Workshop register set',
    categoryId: 'register',
    amount: 1980,
    date: '2026-03-26',
    description: 'Daily inspection and handover registers for workshop desk.',
    vendor: 'Office Orbit',
    tags: ['compliance'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-26T09:10:00+05:30',
    updatedAt: '2026-03-26T12:15:00+05:30',
    receipt: {
      id: 'att-12',
      name: 'register-bill-mar-26.svg',
      url: '/assets/receipts/stationery-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-03-26T09:10:00+05:30',
        'Submitted for workshop documentation cycle.',
      ),
      {
        id: 'register-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-26T12:15:00+05:30',
        note: 'Routine documentation spend approved.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1013',
    title: 'Reception diary bundle',
    categoryId: 'diary',
    amount: 1720,
    date: '2026-04-01',
    description: 'Appointment and reception diary set for April planning.',
    vendor: 'Office Orbit',
    tags: ['front-office'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-01T08:55:00+05:30',
    updatedAt: '2026-04-01T11:05:00+05:30',
    receipt: {
      id: 'att-13',
      name: 'diary-bill-apr-01.svg',
      url: '/assets/receipts/stationery-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-01T08:55:00+05:30',
        'Submitted with front desk replenishment note.',
      ),
      {
        id: 'diary-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T11:05:00+05:30',
        note: 'Front office stationery approved.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1014',
    title: 'Laptop SSD upgrade',
    categoryId: 'laptop',
    amount: 28650,
    date: '2026-03-24',
    description: 'SSD upgrade and service package for reporting workstation.',
    vendor: 'Binary Dock',
    tags: ['it', 'upgrade'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-24T10:40:00+05:30',
    updatedAt: '2026-03-24T16:40:00+05:30',
    receipt: {
      id: 'att-14',
      name: 'laptop-upgrade-mar-24.svg',
      url: '/assets/receipts/hardware-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-03-24T10:40:00+05:30',
        'Submitted with service engineer report.',
      ),
      {
        id: 'laptop-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-24T16:40:00+05:30',
        note: 'Capex tagged under approved workstation refresh.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1015',
    title: 'Monitor arm repair',
    categoryId: 'furniture-repairs',
    amount: 4680,
    date: '2026-04-02',
    description: 'Repair of monitor arm and conference desk cable tray.',
    vendor: 'FixRight Services',
    tags: ['repairs'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-02T13:05:00+05:30',
    updatedAt: '2026-04-02T13:05:00+05:30',
    receipt: {
      id: 'att-15',
      name: 'repair-bill-apr-02.svg',
      url: '/assets/receipts/repair-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Meera Joshi',
      Role.OperationManager,
      '2026-04-02T13:05:00+05:30',
      'Submitted with maintenance log reference.',
    ),
  },
  {
    id: 'exp-1016',
    title: 'Utility consumables pack',
    categoryId: 'utility-consumables',
    amount: 3140,
    date: '2026-03-25',
    description: 'Extension board fuses, bulbs and cable ties for facility upkeep.',
    vendor: 'Prime Utility House',
    tags: ['maintenance'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-25T14:25:00+05:30',
    updatedAt: '2026-03-25T16:55:00+05:30',
    receipt: {
      id: 'att-16',
      name: 'utility-bill-mar-25.svg',
      url: '/assets/receipts/utility-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-03-25T14:25:00+05:30',
        'Submitted with stock register note.',
      ),
      {
        id: 'utility-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-25T16:55:00+05:30',
        note: 'Approved as routine facility upkeep.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1017',
    title: 'Miscellaneous courier charge',
    categoryId: 'miscellaneous',
    amount: 980,
    date: '2026-04-01',
    description: 'Courier charge for registration documents.',
    vendor: 'Swift Desk Express',
    tags: ['courier'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Rejected,
    createdAt: '2026-04-01T17:40:00+05:30',
    updatedAt: '2026-04-01T18:20:00+05:30',
    receipt: {
      id: 'att-17',
      name: 'courier-bill-apr-01.svg',
      url: '/assets/receipts/misc-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-01T17:40:00+05:30',
        'Submitted under miscellaneous operations support.',
      ),
      {
        id: 'courier-rejected',
        action: 'Rejected by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T18:20:00+05:30',
        note: 'Please allocate this to logistics cost center instead.',
        tone: 'danger',
      },
    ],
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'not-1',
    title: 'Tea and Pantry is nearing limit',
    message:
      'Pantry utilization crossed 81 percent for April. Plan the next purchase carefully.',
    date: '2026-04-02T10:30:00+05:30',
    tone: 'warning',
    audience: 'all',
    read: false,
  },
  {
    id: 'not-2',
    title: 'Keyboard category exceeded budget',
    message:
      'A keyboard replacement pushed the category over its monthly limit by 2 percent.',
    date: '2026-04-01T14:21:00+05:30',
    tone: 'danger',
    audience: Role.Admin,
    read: false,
  },
  {
    id: 'not-3',
    title: 'Two expenses pending review',
    message: 'Gas refill and printer toner purchases need finance review today.',
    date: '2026-04-02T11:48:00+05:30',
    tone: 'info',
    audience: Role.Admin,
    read: false,
  },
  {
    id: 'not-4',
    title: 'Draft expense saved',
    message: 'Your paper stock expense is still in draft and can be submitted any time.',
    date: '2026-04-02T16:13:00+05:30',
    tone: 'info',
    audience: Role.OperationManager,
    read: true,
  },
  {
    id: 'not-5',
    title: 'Internet spend approved',
    message: 'Recurring broadband booster pack has been approved for the March cycle.',
    date: '2026-03-27T12:05:00+05:30',
    tone: 'success',
    audience: Role.OperationManager,
    read: true,
  },
];

export const DEMO_TRENDS: TrendPoint[] = [
  { label: 'Nov', total: 128500, budget: 145000, comparison: 7 },
  { label: 'Dec', total: 137900, budget: 145000, comparison: 4 },
  { label: 'Jan', total: 141300, budget: 150000, comparison: 2 },
  { label: 'Feb', total: 152200, budget: 155000, comparison: 8 },
  { label: 'Mar', total: 163400, budget: 165000, comparison: 6 },
  { label: 'Apr', total: 119860, budget: 165000, comparison: -3 },
];

export const DEMO_INSIGHTS: InsightCard[] = [
  {
    id: 'insight-1',
    title: 'Monthly spend momentum',
    description: 'This month exceeded last month by 11.4 percent in hardware-led categories.',
    tone: 'warning',
    delta: 11.4,
  },
  {
    id: 'insight-2',
    title: 'Approval turnaround',
    description: 'Average mock approval cycle is 3.2 hours for routine categories.',
    tone: 'success',
    delta: -18,
  },
  {
    id: 'insight-3',
    title: 'Budget efficiency',
    description:
      'Facilities and pantry categories are still operating 9 percent under combined plan.',
    tone: 'info',
    delta: 9,
  },
];
