import {
  Budget,
  Category,
  Expense,
  ExpenseStatus,
  InsightCard,
  Location,
  NotificationItem,
  Role,
  TrendPoint,
  User,
} from '../models/app.models';

export const DEMO_USERS: User[] = [
  {
    id: 'usr-req-1',
    name: 'Operation Manager',
    email: 'operations.manager.ems@gmail.com',
    role: Role.OperationManager,
    title: 'Operation Manager',
    department: 'Operations',
    avatarUrl: '/assets/avatars/manager-avatar.svg',
    assignedBudget: 45000,
    phone: '+91 98100 12001',
    location: 'North Hub',
  },
  {
    id: 'usr-hr-1',
    name: 'Recommender Team',
    email: 'recommender.ems@gmail.com',
    role: Role.Recommender,
    title: 'Expense Recommender',
    department: 'Review Operations',
    avatarUrl: '/assets/avatars/manager-secondary.svg',
    assignedBudget: 0,
    phone: '+91 98100 12002',
    location: 'Central Hub',
  },
  {
    id: 'usr-admin-1',
    name: 'Admin Team',
    email: 'admin.ems@gmail.com',
    role: Role.Admin,
    title: 'Final Approver',
    department: 'Enterprise Finance',
    avatarUrl: '/assets/avatars/admin-avatar.svg',
    assignedBudget: 275000,
    phone: '+91 98765 43010',
    location: 'Corporate Hub',
  },
  {
    id: 'usr-mgr-1',
    name: 'Operations Manager A',
    email: 'ops.north.ems@gmail.com',
    role: Role.OperationManager,
    title: 'Operations Manager',
    department: 'Operations',
    avatarUrl: '/assets/avatars/manager-avatar.svg',
    assignedBudget: 85000,
    phone: '+91 99887 66125',
    location: 'South Hub',
  },
  {
    id: 'usr-mgr-2',
    name: 'Operations Manager B',
    email: 'ops.east.ems@gmail.com',
    role: Role.OperationManager,
    title: 'Branch Operations Lead',
    department: 'Regional Operations',
    avatarUrl: '/assets/avatars/manager-secondary.svg',
    assignedBudget: 72000,
    phone: '+91 90001 22981',
    location: 'East Hub',
  },
  {
    id: 'usr-mgr-3',
    name: 'Operations Manager C',
    email: 'ops.west.ems@gmail.com',
    role: Role.OperationManager,
    title: 'Facilities Manager',
    department: 'Facilities',
    avatarUrl: '/assets/avatars/manager-third.svg',
    assignedBudget: 64000,
    phone: '+91 97654 11822',
    location: 'West Hub',
  },
];

export const DEMO_CATEGORIES: Category[] = [
  {
    id: 'tea-pantry',
    name: 'Tea and Pantry',
    description: 'Tea, sugar, cups and pantry essentials.',
    icon: 'cup',
    accent: '#06B6D4',
    monthlyBudget: 20000,
    previousSpend: 17240,
  },
  {
    id: 'milk',
    name: 'Milk',
    description: 'Fresh milk and dairy replenishment.',
    icon: 'droplet',
    accent: '#8B5CF6',
    monthlyBudget: 6000,
    previousSpend: 4820,
  },
  {
    id: 'gas',
    name: 'Gas',
    description: 'Refills for pantry and office cooking gas.',
    icon: 'flame',
    accent: '#F59E0B',
    monthlyBudget: 4500,
    previousSpend: 3900,
  },
  {
    id: 'office-snacks',
    name: 'Office Snacks',
    description: 'Snacks for staff and visitors.',
    icon: 'sparkles',
    accent: '#22C55E',
    monthlyBudget: 12000,
    previousSpend: 10820,
  },
  {
    id: 'stationery',
    name: 'Stationery',
    description: 'Mixed office stationery supplies.',
    icon: 'pen-tool',
    accent: '#4F46E5',
    monthlyBudget: 9000,
    previousSpend: 7420,
  },
  {
    id: 'pen',
    name: 'Pen',
    description: 'Pens and marker purchases.',
    icon: 'edit',
    accent: '#38BDF8',
    monthlyBudget: 2500,
    previousSpend: 1980,
  },
  {
    id: 'diary',
    name: 'Diary',
    description: 'Office diaries and planner notebooks.',
    icon: 'book-open',
    accent: '#A78BFA',
    monthlyBudget: 3000,
    previousSpend: 2240,
  },
  {
    id: 'register',
    name: 'Register',
    description: 'Attendance, visitor, and operations registers.',
    icon: 'book',
    accent: '#0EA5E9',
    monthlyBudget: 3200,
    previousSpend: 2625,
  },
  {
    id: 'laptop',
    name: 'Laptop',
    description: 'Laptop procurement and service accessories.',
    icon: 'laptop',
    accent: '#06B6D4',
    monthlyBudget: 55000,
    previousSpend: 41000,
  },
  {
    id: 'keyboard',
    name: 'Keyboard',
    description: 'Replacement keyboards.',
    icon: 'keyboard',
    accent: '#7C3AED',
    monthlyBudget: 6000,
    previousSpend: 5280,
  },
  {
    id: 'mouse',
    name: 'Mouse',
    description: 'USB and wireless mouse replacements.',
    icon: 'mouse-pointer',
    accent: '#22C55E',
    monthlyBudget: 4500,
    previousSpend: 3200,
  },
  {
    id: 'monitor',
    name: 'Monitor',
    description: 'Display accessories and replacements.',
    icon: 'monitor',
    accent: '#2563EB',
    monthlyBudget: 24000,
    previousSpend: 19850,
  },
  {
    id: 'printer-items',
    name: 'Printer Items',
    description: 'Toners, cartridges and maintenance items.',
    icon: 'printer',
    accent: '#F97316',
    monthlyBudget: 14000,
    previousSpend: 11890,
  },
  {
    id: 'paper',
    name: 'Paper',
    description: 'A4, invoice and printer paper stock.',
    icon: 'file-text',
    accent: '#94A3B8',
    monthlyBudget: 5000,
    previousSpend: 4150,
  },
  {
    id: 'internet',
    name: 'Internet',
    description: 'Broadband and backup data charges.',
    icon: 'wifi',
    accent: '#06B6D4',
    monthlyBudget: 9000,
    previousSpend: 8700,
  },
  {
    id: 'cleaning-supplies',
    name: 'Cleaning Supplies',
    description: 'Cleaning liquids, wipes and consumables.',
    icon: 'shield',
    accent: '#10B981',
    monthlyBudget: 7000,
    previousSpend: 5640,
  },
  {
    id: 'furniture-repairs',
    name: 'Workspace Maintenance',
    description: 'Minor workspace upkeep, fixtures, and office support items.',
    icon: 'tool',
    accent: '#F59E0B',
    monthlyBudget: 16000,
    previousSpend: 12500,
  },
  {
    id: 'utility-consumables',
    name: 'Utility Consumables',
    description: 'Daily operational consumables.',
    icon: 'package',
    accent: '#6366F1',
    monthlyBudget: 11000,
    previousSpend: 9325,
  },
  {
    id: 'miscellaneous',
    name: 'Miscellaneous',
    description: 'Small ad hoc office expenses.',
    icon: 'asterisk',
    accent: '#EF4444',
    monthlyBudget: 8000,
    previousSpend: 7340,
  },
  {
    id: 'staff-fooding',
    name: 'Staff Fooding Expense',
    description: 'Team meal and extended shift fooding expense.',
    icon: 'sparkles',
    accent: '#22C55E',
    monthlyBudget: 18000,
    previousSpend: 14280,
  },
  {
    id: 'customer-facility',
    name: 'Customer Facility Expense',
    description: 'Refreshments and comfort items for customers.',
    icon: 'cup',
    accent: '#06B6D4',
    monthlyBudget: 15000,
    previousSpend: 11950,
  },
  {
    id: 'staff-tea',
    name: 'Staff Tea Expenses',
    description: 'Dedicated staff tea service and beverage support.',
    icon: 'cup',
    accent: '#8B5CF6',
    monthlyBudget: 9000,
    previousSpend: 6840,
  },
];

export const DEMO_LOCATIONS: Location[] = [
  { id: 'loc-hq', name: 'Bengaluru Head Office', city: 'Bengaluru', code: 'BLR-HQ', active: true },
  { id: 'loc-west', name: 'Pune Branch', city: 'Pune', code: 'PUN-BR', active: true },
  { id: 'loc-south', name: 'Hyderabad Support Office', city: 'Hyderabad', code: 'HYD-SO', active: true },
];

export const DEMO_BUDGETS: Budget[] = [
  {
    id: 'bud-1',
    categoryId: 'tea-pantry',
    locationId: 'loc-hq',
    annualBudget: 240000,
    spent: 198000,
    active: true,
    notes: 'Primary pantry supplies for the main office.',
    updatedAt: '2026-04-01T09:00:00+05:30',
  },
  {
    id: 'bud-2',
    categoryId: 'stationery',
    locationId: 'loc-west',
    annualBudget: 105000,
    spent: 78500,
    active: true,
    notes: 'Regional stationery and office stock.',
    updatedAt: '2026-04-01T09:10:00+05:30',
  },
  {
    id: 'bud-3',
    categoryId: 'internet',
    locationId: 'loc-south',
    annualBudget: 96000,
    spent: 71200,
    active: true,
    notes: 'Connectivity and backup internet support.',
    updatedAt: '2026-04-01T09:20:00+05:30',
  },
];

const commonAudit = (actor: string, actorRole: Role, date: string, note: string) => [
  {
    id: `${actor}-${date}-created`,
    action: 'Expense logged',
    actor,
    actorRole,
    date,
    note,
    tone: 'info' as const,
  },
];

export const DEMO_EXPENSES: Expense[] = [
  {
    id: 'exp-2001',
    title: 'Team laptop adaptor replacement',
    categoryId: 'laptop',
    locationId: 'loc-hq',
    employeeId: 'usr-req-1',
    amount: 2890,
    date: '2026-04-10',
    description: 'Replacement adaptor for day-long support shifts.',
    vendor: 'Dell Business Store',
    tags: ['hardware', 'replacement'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-10T09:20:00+05:30',
    updatedAt: '2026-04-10T09:20:00+05:30',
    receipt: {
      id: 'att-2001',
      name: 'laptop-adaptor-apr-10.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: commonAudit(
      'Employee One',
      Role.OperationManager,
      '2026-04-10T09:20:00+05:30',
      'Submitted for recommender review with bill preview.',
    ),
    remarks: ['Please verify against the approved hardware policy.'],
  },
  {
    id: 'exp-2002',
    title: 'Cab fare for client visit',
    categoryId: 'utility-consumables',
    locationId: 'loc-west',
    employeeId: 'usr-req-1',
    amount: 860,
    date: '2026-04-11',
    description: 'Local travel for a short client service visit.',
    vendor: 'QuickRide',
    tags: ['travel', 'local'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Recommended,
    createdAt: '2026-04-11T10:10:00+05:30',
    updatedAt: '2026-04-11T12:40:00+05:30',
    receipt: {
      id: 'att-2002',
      name: 'cab-fare-apr-11.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-11T10:10:00+05:30',
        'Submitted after the client visit.',
      ),
      {
        id: 'apr-11-hr',
        action: 'Recommended by recommender',
        actor: 'Reviewer Team',
        actorRole: Role.Recommender,
        date: '2026-04-11T12:40:00+05:30',
        note: 'Travel expense is within policy and can move to final approval.',
        tone: 'success',
      },
    ],
    remarks: ['Recommender checked route and attached bill.'],
  },
  {
    id: 'exp-2003',
    title: 'Meal allowance cancellation',
    categoryId: 'staff-fooding',
    locationId: 'loc-south',
    employeeId: 'usr-req-1',
    amount: 540,
    date: '2026-04-08',
    description: 'Meal claim cancelled after duplicate upload was found.',
    vendor: 'Food Plaza',
    tags: ['meal', 'cancelled'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Cancelled,
    createdAt: '2026-04-08T14:05:00+05:30',
    updatedAt: '2026-04-08T15:00:00+05:30',
    receipt: {
      id: 'att-2003',
      name: 'meal-cancelled-apr-08.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-08T14:05:00+05:30',
        'Submitted, then cancelled by the operation manager after duplicate entry was noticed.',
      ),
      {
        id: 'apr-08-cancel',
        action: 'Cancelled by operation manager',
        actor: 'Employee One',
        actorRole: Role.OperationManager,
        date: '2026-04-08T15:00:00+05:30',
        note: 'Request cancelled before recommender review.',
        tone: 'warning',
      },
    ],
    remarks: ['Cancelled before queue processing.'],
  },
  {
    id: 'exp-2004',
    title: 'Client visit stationery kit',
    categoryId: 'stationery',
    locationId: 'loc-hq',
    employeeId: 'usr-req-1',
    amount: 1240,
    date: '2026-04-12',
    description: 'Notebooks and pens used during a client meeting and follow-up notes.',
    vendor: 'Stationery Hub',
    tags: ['stationery', 'client'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-12T09:15:00+05:30',
    updatedAt: '2026-04-12T09:15:00+05:30',
    receipt: {
      id: 'att-2004',
      name: 'stationery-kit-apr-12.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: commonAudit(
      'Employee One',
      Role.OperationManager,
      '2026-04-12T09:15:00+05:30',
      'Submitted with bill preview attached for review.',
    ),
    remarks: ['Purchased for client-facing meeting notes.'],
  },
  {
    id: 'exp-2005',
    title: 'Visitor snack tray correction',
    categoryId: 'office-snacks',
    locationId: 'loc-west',
    employeeId: 'usr-req-1',
    amount: 960,
    date: '2026-04-13',
    description: 'Snack purchase corrected after recommender review with updated bill copy.',
    vendor: 'Snack Basket',
    tags: ['snacks', 'visitors'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Recommended,
    createdAt: '2026-04-13T11:20:00+05:30',
    updatedAt: '2026-04-13T13:10:00+05:30',
    receipt: {
      id: 'att-2005',
      name: 'visitor-snacks-apr-13.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-13T11:20:00+05:30',
        'Submitted after guest refreshment purchase.',
      ),
      {
        id: 'apr-13-hr',
        action: 'Recommended by recommender',
        actor: 'Reviewer Team',
        actorRole: Role.Recommender,
        date: '2026-04-13T13:10:00+05:30',
        note: 'Bill looks correct after minor clarification on quantity.',
        tone: 'success',
      },
    ],
    remarks: ['Recommender asked for a cleaner bill copy and updated memo.'],
  },
  {
    id: 'exp-2006',
    title: 'Laptop stand purchase',
    categoryId: 'laptop',
    locationId: 'loc-south',
    employeeId: 'usr-req-1',
    amount: 3140,
    date: '2026-04-14',
    description: 'Ergonomic laptop stand for long working sessions.',
    vendor: 'Office Tech World',
    tags: ['ergonomic', 'hardware'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-14T08:30:00+05:30',
    updatedAt: '2026-04-14T16:25:00+05:30',
    receipt: {
      id: 'att-2006',
      name: 'laptop-stand-apr-14.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-14T08:30:00+05:30',
        'Submitted with product details and receipt.',
      ),
      {
        id: 'apr-14-hr',
        action: 'Recommended by recommender',
        actor: 'Reviewer Team',
        actorRole: Role.Recommender,
        date: '2026-04-14T11:05:00+05:30',
        note: 'Equipment is useful for daily work and within policy.',
        tone: 'success',
      },
      {
        id: 'apr-14-admin',
        action: 'Final approved by admin',
        actor: 'Approver Team',
        actorRole: Role.Admin,
        date: '2026-04-14T16:25:00+05:30',
        note: 'Approved for direct work support usage.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-2007',
    title: 'Fuel reimbursement follow-up',
    categoryId: 'utility-consumables',
    locationId: 'loc-hq',
    employeeId: 'usr-req-1',
    amount: 780,
    date: '2026-04-15',
    description: 'Reopened fuel reimbursement pending a corrected route note.',
    vendor: 'City Fuel',
    tags: ['travel', 'fuel'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Reopened,
    createdAt: '2026-04-15T10:00:00+05:30',
    updatedAt: '2026-04-15T12:45:00+05:30',
    receipt: {
      id: 'att-2007',
      name: 'fuel-reimbursement-apr-15.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-15T10:00:00+05:30',
        'Submitted with route note for local travel.',
      ),
      {
        id: 'apr-15-hr',
        action: 'Reopened by recommender',
        actor: 'Reviewer Team',
        actorRole: Role.Recommender,
        date: '2026-04-15T12:45:00+05:30',
        note: 'Please add the revised route note before resubmission.',
        tone: 'warning',
      },
    ],
    remarks: ['Awaiting corrected route note from operation manager.'],
  },
  {
    id: 'exp-2008',
    title: 'Printer cartridge pickup',
    categoryId: 'printer-items',
    locationId: 'loc-hq',
    employeeId: 'usr-req-1',
    amount: 2140,
    date: '2026-04-16',
    description: 'Urgent cartridge replacement for the front office printer.',
    vendor: 'PrintMate Supplies',
    tags: ['printer', 'urgent'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-16T09:05:00+05:30',
    updatedAt: '2026-04-16T09:05:00+05:30',
    receipt: {
      id: 'att-2008',
      name: 'printer-cartridge-apr-16.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: commonAudit(
      'Employee One',
      Role.OperationManager,
      '2026-04-16T09:05:00+05:30',
      'Submitted for expense review with receipt preview.',
    ),
    remarks: ['Requested for same-day printer support.'],
  },
  {
    id: 'exp-2009',
    title: 'Visitor water bottles',
    categoryId: 'customer-facility',
    locationId: 'loc-west',
    employeeId: 'usr-req-1',
    amount: 1120,
    date: '2026-04-16',
    description: 'Water bottles arranged for a short afternoon guest meeting.',
    vendor: 'AquaPlus Mart',
    tags: ['visitors', 'facility'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-16T11:30:00+05:30',
    updatedAt: '2026-04-16T17:00:00+05:30',
    receipt: {
      id: 'att-2009',
      name: 'water-bottles-apr-16.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-16T11:30:00+05:30',
        'Submitted after guest refreshments were arranged.',
      ),
      {
        id: 'apr-16-hr',
        action: 'Recommended by recommender',
        actor: 'Reviewer Team',
        actorRole: Role.Recommender,
        date: '2026-04-16T14:00:00+05:30',
        note: 'Routine facility spend approved for final review.',
        tone: 'success',
      },
      {
        id: 'apr-16-admin',
        action: 'Approved by admin',
        actor: 'Approver Team',
        actorRole: Role.Admin,
        date: '2026-04-16T17:00:00+05:30',
        note: 'Approved as a normal operational expense.',
        tone: 'success',
      },
    ],
    remarks: ['Approved after recommender confirmation.'],
  },
  {
    id: 'exp-2010',
    title: 'Office chair adjustment kit',
    categoryId: 'furniture-repairs',
    locationId: 'loc-south',
    employeeId: 'usr-req-1',
    amount: 2680,
    date: '2026-04-17',
    description: 'Adjustment kit and small parts for an office chair comfort issue.',
    vendor: 'ComfortFix Office',
    tags: ['repairs', 'furniture'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Rejected,
    createdAt: '2026-04-17T09:50:00+05:30',
    updatedAt: '2026-04-17T12:10:00+05:30',
    receipt: {
      id: 'att-2010',
      name: 'chair-kit-apr-17.pdf',
      url: '/assets/receipt.svg',
      mimeType: 'application/pdf',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-17T09:50:00+05:30',
        'Submitted with item details and supporting quotation.',
      ),
      {
        id: 'apr-17-admin',
        action: 'Rejected by admin',
        actor: 'Approver Team',
        actorRole: Role.Admin,
        date: '2026-04-17T12:10:00+05:30',
        note: 'Please split this into smaller line items with clearer vendor detail.',
        tone: 'danger',
      },
    ],
    remarks: ['Rejected pending clearer item-wise breakdown.'],
  },
  {
    id: 'exp-1001',
    title: 'Pantry refresh for showroom team',
    categoryId: 'tea-pantry',
    amount: 4850,
    date: '2026-04-01',
    description:
      'Tea leaves, sugar, disposable cups and coffee sachets for the first week of April.',
    vendor: 'Fresh Brew Traders',
    tags: ['pantry', 'weekly'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-01T09:45:00+05:30',
    updatedAt: '2026-04-01T12:30:00+05:30',
    receipt: {
      id: 'att-1',
      name: 'pantry-bill-apr-01.svg',
      url: '/assets/receipts/pantry-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-01T09:45:00+05:30',
        'Submitted with bill preview attached.',
      ),
      {
        id: 'apr-01-review',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T12:30:00+05:30',
        note: 'Within allocated pantry budget.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1002',
    title: 'Milk top-up for visitor lounge',
    categoryId: 'milk',
    amount: 1680,
    date: '2026-04-02',
    description: 'Morning dairy purchase for staff pantry and guest counter.',
    vendor: 'Metro Dairy Point',
    tags: ['daily', 'pantry'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-02T10:05:00+05:30',
    updatedAt: '2026-04-02T10:05:00+05:30',
    receipt: {
      id: 'att-2',
      name: 'milk-bill-apr-02.svg',
      url: '/assets/receipts/milk-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Rhea Sharma',
      Role.OperationManager,
      '2026-04-02T10:05:00+05:30',
      'Queued for finance review.',
    ),
  },
  {
    id: 'exp-1003',
    title: 'LPG cylinder refill',
    categoryId: 'gas',
    amount: 2140,
    date: '2026-04-02',
    description: 'Single cylinder refill for cafeteria pantry operations.',
    vendor: 'Prime Gas Agency',
    tags: ['utility'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.UnderReview,
    createdAt: '2026-04-02T11:20:00+05:30',
    updatedAt: '2026-04-02T11:44:00+05:30',
    receipt: {
      id: 'att-3',
      name: 'gas-bill-apr-02.svg',
      url: '/assets/receipts/gas-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-02T11:20:00+05:30',
        'Marked urgent due to pantry downtime.',
      ),
      {
        id: 'gas-check',
        action: 'Review initiated',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-02T11:44:00+05:30',
        note: 'Cross-checking vendor amount versus last refill.',
        tone: 'warning',
      },
    ],
  },
  {
    id: 'exp-1004',
    title: 'Office snack replenishment',
    categoryId: 'office-snacks',
    amount: 6980,
    date: '2026-03-29',
    description: 'Granola bars, biscuits and bottled juice for weekend sales activity.',
    vendor: 'City Wholesale Mart',
    tags: ['staff-engagement'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-29T15:12:00+05:30',
    updatedAt: '2026-03-29T18:25:00+05:30',
    receipt: {
      id: 'att-4',
      name: 'snacks-bill-mar-29.svg',
      url: '/assets/receipts/snacks-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-03-29T15:12:00+05:30',
        'Submitted for event-day usage.',
      ),
      {
        id: 'snacks-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-29T18:25:00+05:30',
        note: 'Aligned to dealership weekend campaign.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1004a',
    title: 'Tea pantry premium refill',
    categoryId: 'tea-pantry',
    amount: 16240,
    date: '2026-04-03',
    description: 'Extra tea, coffee and disposable cups for the month-end visitor rush.',
    vendor: 'Fresh Brew Traders',
    tags: ['pantry', 'month-end'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-03T09:10:00+05:30',
    updatedAt: '2026-04-03T09:10:00+05:30',
    receipt: {
      id: 'att-4a',
      name: 'pantry-bill-apr-03.svg',
      url: '/assets/receipts/pantry-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Rhea Sharma',
      Role.OperationManager,
      '2026-04-03T09:10:00+05:30',
      'Submitted for month-end pantry usage.',
    ),
  },
  {
    id: 'exp-1004b',
    title: 'Office snack top-up',
    categoryId: 'office-snacks',
    amount: 6125,
    date: '2026-04-03',
    description: 'Visitor snack tray refills and tea-time supplies.',
    vendor: 'City Wholesale Mart',
    tags: ['staff-engagement', 'monthly'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-03T11:25:00+05:30',
    updatedAt: '2026-04-03T11:25:00+05:30',
    receipt: {
      id: 'att-4b',
      name: 'snacks-bill-apr-03.svg',
      url: '/assets/receipts/snacks-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Rhea Sharma',
      Role.OperationManager,
      '2026-04-03T11:25:00+05:30',
      'Submitted for month-end visitor handling.',
    ),
  },
  {
    id: 'exp-1005',
    title: 'Stationery combo pack',
    categoryId: 'stationery',
    amount: 4325,
    date: '2026-04-01',
    description: 'Markers, sticky notes, files and desk stationery.',
    vendor: 'Office Orbit',
    tags: ['supplies'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-01T13:15:00+05:30',
    updatedAt: '2026-04-01T16:10:00+05:30',
    receipt: {
      id: 'att-5',
      name: 'stationery-bill-apr-01.svg',
      url: '/assets/receipts/stationery-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-04-01T13:15:00+05:30',
        'Submitted against regional branch stock requirement.',
      ),
      {
        id: 'stationery-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T16:10:00+05:30',
        note: 'Purchase within approved stationery band.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1006',
    title: 'Premium keyboard replacement',
    categoryId: 'keyboard',
    amount: 6120,
    date: '2026-04-01',
    description: 'Mechanical keyboard replacement for finance control desk.',
    vendor: 'TechSquare Systems',
    tags: ['hardware', 'replacement'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.OverBudget,
    createdAt: '2026-04-01T14:00:00+05:30',
    updatedAt: '2026-04-01T14:20:00+05:30',
    receipt: {
      id: 'att-6',
      name: 'keyboard-bill-apr-01.svg',
      url: '/assets/receipts/hardware-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-04-01T14:00:00+05:30',
        'Submitted with urgent hardware replacement justification.',
      ),
      {
        id: 'keyboard-alert',
        action: 'Over budget flagged',
        actor: 'System',
        actorRole: Role.Admin,
        date: '2026-04-01T14:20:00+05:30',
        note: 'Category has exceeded 100 percent monthly utilization.',
        tone: 'danger',
      },
    ],
  },
  {
    id: 'exp-1007',
    title: 'Printer toner cartridge set',
    categoryId: 'printer-items',
    amount: 8840,
    date: '2026-04-02',
    description: 'Toner cartridge set for invoice printer and reporting printer.',
    vendor: 'PrintEase Solutions',
    tags: ['printing'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.UnderReview,
    createdAt: '2026-04-02T09:20:00+05:30',
    updatedAt: '2026-04-02T10:15:00+05:30',
    receipt: {
      id: 'att-7',
      name: 'printer-bill-apr-02.svg',
      url: '/assets/receipts/printer-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-04-02T09:20:00+05:30',
        'Submitted with vendor quotation attachment.',
      ),
      {
        id: 'printer-review',
        action: 'Review initiated',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-02T10:15:00+05:30',
        note: 'Comparing unit rates with prior purchase cycle.',
        tone: 'warning',
      },
    ],
  },
  {
    id: 'exp-1008',
    title: 'Broadband annual booster pack',
    categoryId: 'internet',
    amount: 9320,
    date: '2026-03-27',
    description: 'Bandwidth booster pack for finance and support systems.',
    vendor: 'SkyWire Business',
    tags: ['connectivity'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-27T10:45:00+05:30',
    updatedAt: '2026-03-27T12:00:00+05:30',
    receipt: {
      id: 'att-8',
      name: 'internet-bill-mar-27.svg',
      url: '/assets/receipts/internet-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-03-27T10:45:00+05:30',
        'Submitted as planned recurring connectivity spend.',
      ),
      {
        id: 'internet-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-27T12:00:00+05:30',
        note: 'Tagged as recurring business utility.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1009',
    title: 'Visitor lounge paper stock',
    categoryId: 'paper',
    amount: 2140,
    date: '2026-04-02',
    description: 'A4 and invoice paper stock replenishment.',
    vendor: 'PaperPort Office',
    tags: ['stock'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Draft,
    createdAt: '2026-04-02T16:12:00+05:30',
    updatedAt: '2026-04-02T16:12:00+05:30',
    receipt: {
      id: 'att-9',
      name: 'paper-bill-draft.svg',
      url: '/assets/receipts/paper-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Rhea Sharma',
      Role.OperationManager,
      '2026-04-02T16:12:00+05:30',
      'Saved as draft for later submission.',
    ),
  },
  {
    id: 'exp-1010',
    title: 'Wireless mouse replacements',
    categoryId: 'mouse',
    amount: 2940,
    date: '2026-03-30',
    description: 'Two wireless mouse replacements for reception and billing desk.',
    vendor: 'TechSquare Systems',
    tags: ['hardware'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-30T11:20:00+05:30',
    updatedAt: '2026-03-30T15:35:00+05:30',
    receipt: {
      id: 'att-10',
      name: 'mouse-bill-mar-30.svg',
      url: '/assets/receipts/hardware-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-03-30T11:20:00+05:30',
        'Submitted with workstation downtime note.',
      ),
      {
        id: 'mouse-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-30T15:35:00+05:30',
        note: 'Approved under workstation maintenance.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1011',
    title: 'Cleaning liquids and wipes',
    categoryId: 'cleaning-supplies',
    amount: 5280,
    date: '2026-03-28',
    description: 'Housekeeping consumables for customer zones and service desks.',
    vendor: 'Spark Hygiene Mart',
    tags: ['housekeeping'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-28T08:35:00+05:30',
    updatedAt: '2026-03-28T10:10:00+05:30',
    receipt: {
      id: 'att-11',
      name: 'cleaning-bill-mar-28.svg',
      url: '/assets/receipts/cleaning-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-03-28T08:35:00+05:30',
        'Submitted as recurring facilities expense.',
      ),
      {
        id: 'cleaning-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-28T10:10:00+05:30',
        note: 'Routine cleaning spend approved.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1012',
    title: 'Operations register set',
    categoryId: 'register',
    amount: 1980,
    date: '2026-03-26',
    description: 'Daily inspection and handover registers for the operations desk.',
    vendor: 'Office Orbit',
    tags: ['compliance'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-26T09:10:00+05:30',
    updatedAt: '2026-03-26T12:15:00+05:30',
    receipt: {
      id: 'att-12',
      name: 'register-bill-mar-26.svg',
      url: '/assets/receipts/stationery-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-03-26T09:10:00+05:30',
        'Submitted for the monthly operations documentation cycle.',
      ),
      {
        id: 'register-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-26T12:15:00+05:30',
        note: 'Routine documentation spend approved.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1013',
    title: 'Reception diary bundle',
    categoryId: 'diary',
    amount: 1720,
    date: '2026-04-01',
    description: 'Appointment and reception diary set for April planning.',
    vendor: 'Office Orbit',
    tags: ['front-office'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Approved,
    createdAt: '2026-04-01T08:55:00+05:30',
    updatedAt: '2026-04-01T11:05:00+05:30',
    receipt: {
      id: 'att-13',
      name: 'diary-bill-apr-01.svg',
      url: '/assets/receipts/stationery-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-01T08:55:00+05:30',
        'Submitted with front desk replenishment note.',
      ),
      {
        id: 'diary-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T11:05:00+05:30',
        note: 'Front office stationery approved.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1014',
    title: 'Laptop SSD upgrade',
    categoryId: 'laptop',
    amount: 28650,
    date: '2026-03-24',
    description: 'SSD upgrade and service package for reporting workstation.',
    vendor: 'Binary Dock',
    tags: ['it', 'upgrade'],
    managerId: 'usr-mgr-2',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-24T10:40:00+05:30',
    updatedAt: '2026-03-24T16:40:00+05:30',
    receipt: {
      id: 'att-14',
      name: 'laptop-upgrade-mar-24.svg',
      url: '/assets/receipts/hardware-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Kabir Saini',
        Role.OperationManager,
        '2026-03-24T10:40:00+05:30',
        'Submitted with service engineer report.',
      ),
      {
        id: 'laptop-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-24T16:40:00+05:30',
        note: 'Capex tagged under approved workstation refresh.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1015',
    title: 'Monitor arm replacement parts',
    categoryId: 'furniture-repairs',
    amount: 4680,
    date: '2026-04-02',
    description: 'Replacement parts for a monitor arm and conference desk cable tray.',
    vendor: 'FixRight Services',
    tags: ['repairs'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-02T13:05:00+05:30',
    updatedAt: '2026-04-02T13:05:00+05:30',
    receipt: {
      id: 'att-15',
      name: 'workspace-support-bill-apr-02.svg',
      url: '/assets/receipts/repair-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Meera Joshi',
      Role.OperationManager,
      '2026-04-02T13:05:00+05:30',
      'Submitted with workspace support log reference.',
    ),
  },
  {
    id: 'exp-1016',
    title: 'Utility consumables pack',
    categoryId: 'utility-consumables',
    amount: 3140,
    date: '2026-03-25',
    description: 'Extension board fuses, bulbs and cable ties for facility upkeep.',
    vendor: 'Prime Utility House',
    tags: ['maintenance'],
    managerId: 'usr-mgr-3',
    status: ExpenseStatus.Approved,
    createdAt: '2026-03-25T14:25:00+05:30',
    updatedAt: '2026-03-25T16:55:00+05:30',
    receipt: {
      id: 'att-16',
      name: 'utility-bill-mar-25.svg',
      url: '/assets/receipts/utility-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Meera Joshi',
        Role.OperationManager,
        '2026-03-25T14:25:00+05:30',
        'Submitted with stock register note.',
      ),
      {
        id: 'utility-approved',
        action: 'Approved by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-03-25T16:55:00+05:30',
        note: 'Approved as routine facility upkeep.',
        tone: 'success',
      },
    ],
  },
  {
    id: 'exp-1017',
    title: 'Miscellaneous courier charge',
    categoryId: 'miscellaneous',
    amount: 980,
    date: '2026-04-01',
    description: 'Courier charge for registration documents.',
    vendor: 'Swift Desk Express',
    tags: ['courier'],
    managerId: 'usr-mgr-1',
    status: ExpenseStatus.Rejected,
    createdAt: '2026-04-01T17:40:00+05:30',
    updatedAt: '2026-04-01T18:20:00+05:30',
    receipt: {
      id: 'att-17',
      name: 'courier-bill-apr-01.svg',
      url: '/assets/receipts/misc-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Rhea Sharma',
        Role.OperationManager,
        '2026-04-01T17:40:00+05:30',
        'Submitted under miscellaneous operations support.',
      ),
      {
        id: 'courier-rejected',
        action: 'Rejected by finance',
        actor: 'Aarav Malhotra',
        actorRole: Role.Admin,
        date: '2026-04-01T18:20:00+05:30',
        note: 'Please allocate this to logistics cost center instead.',
        tone: 'danger',
      },
    ],
  },
  {
    id: 'exp-1018',
    title: 'Paper stock refill for reception',
    categoryId: 'paper',
    locationId: 'loc-hq',
    employeeId: 'usr-req-1',
    amount: 2680,
    date: '2026-04-03',
    description: 'A4 paper and letterhead stock for front desk and billing.',
    vendor: 'PaperPort Office',
    tags: ['reception', 'stock'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Reopened,
    createdAt: '2026-04-03T09:35:00+05:30',
    updatedAt: '2026-04-03T12:10:00+05:30',
    receipt: {
      id: 'att-18',
      name: 'paper-stock-apr-03.svg',
      url: '/assets/receipts/paper-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-03T09:35:00+05:30',
        'Submitted with reception stock note.',
      ),
      {
        id: 'paper-hr',
        action: 'Recommended by recommender',
        actor: 'Reviewer Team',
        actorRole: Role.Recommender,
        date: '2026-04-03T11:05:00+05:30',
        note: 'Request looked valid, but the category budget needs a smaller split.',
        tone: 'warning',
      },
      {
        id: 'paper-reopen',
        action: 'Reopened by admin',
        actor: 'Approver Team',
        actorRole: Role.Admin,
        date: '2026-04-03T12:10:00+05:30',
        note: 'Please resubmit with vendor line-item details.',
        tone: 'info',
      },
    ],
    remarks: ['Please add vendor breakup before approval.'],
  },
  {
    id: 'exp-1019',
    title: 'Training lunch for support desk',
    categoryId: 'staff-fooding',
    locationId: 'loc-west',
    employeeId: 'usr-req-1',
    amount: 4120,
    date: '2026-04-04',
    description: 'Lunch for the extended training session with support staff.',
    vendor: 'City Pantry Kitchen',
    tags: ['training', 'food'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Recommended,
    createdAt: '2026-04-04T13:00:00+05:30',
    updatedAt: '2026-04-04T15:20:00+05:30',
    receipt: {
      id: 'att-19',
      name: 'training-lunch-apr-04.svg',
      url: '/assets/receipts/snacks-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
        Role.OperationManager,
        '2026-04-04T13:00:00+05:30',
        'Submitted after support training completed.',
      ),
      {
        id: 'training-lunch-hr',
        action: 'Recommended by recommender',
        actor: 'Reviewer Team',
        actorRole: Role.Recommender,
        date: '2026-04-04T15:20:00+05:30',
        note: 'Guest count and purpose are clear for final approval.',
        tone: 'success',
      },
    ],
    remarks: ['Recommender reviewed after training check.'],
  },
  {
    id: 'exp-1020',
    title: 'Branch stationery top-up',
    categoryId: 'stationery',
    locationId: 'loc-south',
    employeeId: 'usr-req-1',
    amount: 1850,
    date: '2026-04-05',
    description: 'Staplers, pens, and file folders for the Hyderabad support office.',
    vendor: 'Office Orbit',
    tags: ['branch', 'stationery'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Submitted,
    createdAt: '2026-04-05T10:45:00+05:30',
    updatedAt: '2026-04-05T10:45:00+05:30',
    receipt: {
      id: 'att-20',
      name: 'stationery-topup-apr-05.svg',
      url: '/assets/receipts/stationery-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: commonAudit(
      'Employee One',
      Role.OperationManager,
      '2026-04-05T10:45:00+05:30',
      'Submitted from branch office desk.',
    ),
  },
  {
    id: 'exp-1021',
    title: 'Visitor lounge snacks correction',
    categoryId: 'office-snacks',
    locationId: 'loc-hq',
    employeeId: 'usr-req-1',
    amount: 1240,
    date: '2026-04-05',
    description: 'Snack purchase corrected after duplicate receipt validation.',
    vendor: 'Fresh Brew Traders',
    tags: ['correction', 'snacks'],
    managerId: 'usr-req-1',
    status: ExpenseStatus.Rejected,
    createdAt: '2026-04-05T11:10:00+05:30',
    updatedAt: '2026-04-05T13:15:00+05:30',
    receipt: {
      id: 'att-21',
      name: 'snacks-correction-apr-05.svg',
      url: '/assets/receipts/snacks-receipt.svg',
      mimeType: 'image/svg+xml',
    },
    auditTrail: [
      ...commonAudit(
        'Employee One',
      Role.OperationManager,
        '2026-04-05T11:10:00+05:30',
        'Submitted with duplicate bill note.',
      ),
      {
        id: 'snacks-rejected',
        action: 'Rejected by finance',
        actor: 'Approver Team',
        actorRole: Role.Admin,
        date: '2026-04-05T13:15:00+05:30',
        note: 'Duplicate receipt detected. Please submit only the corrected bill.',
        tone: 'danger',
      },
    ],
    remarks: ['Rejected due to duplicate receipt.'],
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'not-1',
    title: 'Tea and Pantry is nearing limit',
    message:
      'Pantry utilization crossed 81 percent for April. Plan the next purchase carefully.',
    date: '2026-04-02T10:30:00+05:30',
    tone: 'warning',
    audience: 'all',
    read: false,
  },
  {
    id: 'not-2',
    title: 'Keyboard category exceeded budget',
    message:
      'A keyboard replacement pushed the category over its monthly limit by 2 percent.',
    date: '2026-04-01T14:21:00+05:30',
    tone: 'danger',
    audience: Role.Admin,
    read: false,
  },
  {
    id: 'not-3',
    title: 'Two expenses pending review',
    message: 'Gas refill and printer toner purchases need finance review today.',
    date: '2026-04-02T11:48:00+05:30',
    tone: 'info',
    audience: Role.Admin,
    read: false,
  },
  {
    id: 'not-3b',
    title: 'Recommendation queue is ready',
    message: 'There are submitted expenses waiting for recommendation.',
    date: '2026-04-11T12:45:00+05:30',
    tone: 'warning',
    audience: Role.Recommender,
    read: false,
  },
  {
    id: 'not-4',
    title: 'Draft expense saved',
    message: 'Your paper stock expense is still in draft and can be submitted any time.',
    date: '2026-04-02T16:13:00+05:30',
    tone: 'info',
    audience: Role.OperationManager,
    read: true,
  },
  {
    id: 'not-5',
    title: 'Internet spend approved',
    message: 'Recurring broadband booster pack has been approved for the March cycle.',
    date: '2026-03-27T12:05:00+05:30',
    tone: 'success',
    audience: Role.OperationManager,
    read: true,
  },
];

export const DEMO_TRENDS: TrendPoint[] = [
  { label: 'Nov', total: 128500, budget: 145000, comparison: 7 },
  { label: 'Dec', total: 137900, budget: 145000, comparison: 4 },
  { label: 'Jan', total: 141300, budget: 150000, comparison: 2 },
  { label: 'Feb', total: 152200, budget: 155000, comparison: 8 },
  { label: 'Mar', total: 163400, budget: 165000, comparison: 6 },
  { label: 'Apr', total: 119860, budget: 165000, comparison: -3 },
];

export const DEMO_INSIGHTS: InsightCard[] = [
  {
    id: 'insight-1',
    title: 'Monthly spend momentum',
    description: 'This month exceeded last month by 11.4 percent in hardware-led categories.',
    tone: 'warning',
    delta: 11.4,
  },
  {
    id: 'insight-2',
    title: 'Approval turnaround',
    description: 'Average approval cycle is 3.2 hours for routine categories.',
    tone: 'success',
    delta: -18,
  },
  {
    id: 'insight-3',
    title: 'Budget efficiency',
    description:
      'Facilities and pantry categories are still operating 9 percent under combined plan.',
    tone: 'info',
    delta: 9,
  },
];
